### ISSUE TITLE
[1.18] Arclight compatibility

### ISSUE THREAD

**Issue by muriplz** [sachingorkar102/Lootin-plugin#13]
Hello,i'm using this plugin with https://github.com/IzzelAliz/Arclight . 

There are some error logs that get spammed on console. Although the plugins functions nicely on all cases

Using Lootin 5.1 and Arclight c78fe148d33f683183e03fea5c353355f0b9b11b (1.18)

```
[07Aug2022 00:58:24.131] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to Lootin v5.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading}
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:505) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameModeMixin.java:804) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.management.ServerPlayerGameModeMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:realtime.PlayerInteractionManagerMixin_Realtime,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerPlayNetHandlerMixin.java:985) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:8) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.md6580a8$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.PacketThreadUtilMixin,pl:mixin:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:arclight_implementer,re:mixin,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:mixin,re:mixin,re:mixin,re:arclight_implementer}
Caused by: java.lang.NoSuchFieldError: opened
	at org.bukkit.craftbukkit.v1_18_R2.block.CraftChest.open(CraftChest.java:59) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:classloading}
	at com.github.sachin.lootin.gui.ChestGui.open(ChestGui.java:30) ~[?:?] {}
	at com.github.sachin.lootin.listeners.InventoryListeners.onInteract(InventoryListeners.java:77) ~[?:?] {}
	... 22 more
```

```
[07Aug2022 00:58:25.603] [Server thread/ERROR] [Minecraft/]: Could not pass event InventoryCloseEvent to Lootin v5.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading}
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactoryMixin.java:1376) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:A}
	at net.minecraft.server.level.ServerPlayer.handler$zih000$arclight$invClose(ServerPlayerMixin.java:2367) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9230_(ServerPlayerMixin.java) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7951_(ServerPlayNetHandlerMixin.java:1293) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.m_5797_(CCloseWindowPacketMixin.java:15) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CCloseWindowPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.m_5797_(CCloseWindowPacketMixin.java:6) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CCloseWindowPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.md6580a8$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.PacketThreadUtilMixin,pl:mixin:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:arclight_implementer,re:mixin,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:arclight_implementer,re:mixin,re:mixin,re:mixin,re:arclight_implementer}
Caused by: java.lang.NoSuchFieldError: opened
	at org.bukkit.craftbukkit.v1_18_R2.block.CraftChest.close(CraftChest.java:70) ~[arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar%2368!/:arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14] {re:classloading}
	at com.github.sachin.lootin.gui.ChestGui.close(ChestGui.java:44) ~[?:?] {}
	at com.github.sachin.lootin.listeners.InventoryListeners.onInventoryClose(InventoryListeners.java:125) ~[?:?] {}
	... 23 more
```

**Comment by sachingorkar102** [comment]
Sorry, I only support spigot and papermc forks
