### ISSUE TITLE
Error strat server with the active BetterStructures plugin

### ISSUE THREAD

**Issue by antonioscarpino** [sachingorkar102/Lootin-plugin#14]
Error I have at the start of the server with the active BetterStructures plugin.

[10:39:02] [Server thread/INFO]: [Lootin] Enabling Lootin v5.2
[10:39:02] [Server thread/INFO]: [Lootin] Config file reloaded
[10:39:02] [Server thread/INFO]: [Lootin] Found BetterStructures, registering listeners...
[10:39:02] [Server thread/ERROR]: Error occurred while enabling Lootin v5.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.magmaguy.betterstructures.api.ChestFillEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:683) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:616) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.github.sachin.lootin.Lootin.onEnable(Lootin.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Is there the possibility to solve this error?
Thanks for the support

**Comment by sachingorkar102** [comment]
Ya, you might have to wait until a small fix is released on better structures, i tested with preview jar on their discord
