### ISSUE TITLE
1.19.3 not supported

### ISSUE THREAD

**Issue by ElFrod0** [sachingorkar102/Lootin-plugin#17]
Title says it all.

**Comment by ErythroCraft** [comment]
Me too

[18:03:16] [Server thread/INFO]: [Lootin] Enabling Lootin v5.3
[18:03:16] [Server thread/WARN]: java.lang.ClassNotFoundException: com.github.sachin.lootin.prilib.nms.v1_19_R2.NMSHandler
[18:03:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[18:03:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:03:16] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:03:16] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:03:16] [Server thread/WARN]: 	at com.github.sachin.lootin.prilib.Prilib.loadVersions(Prilib.java:64)
[18:03:16] [Server thread/WARN]: 	at com.github.sachin.lootin.prilib.Prilib.initialize(Prilib.java:34)
[18:03:16] [Server thread/WARN]: 	at com.github.sachin.lootin.Lootin.onEnable(Lootin.java:59)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539)
[18:03:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453)
[18:03:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587)
[18:03:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412)
[18:03:16] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[18:03:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[18:03:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[18:03:16] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Michael-A-Sloan** [comment]
Same here

**Comment by MCHalfAssed** [comment]
@Lauriichan Hey! Hope all is well. Would you happen to know if @sachingorkar102 is able to continue working on this plugin?

It would be very helpful to have just a communication update - Though I know it's not always easy when you lose passion/time for a project.

If possible, I would like to discuss making this plugin open source so others can continue development on it. Let me know your thoughts, thanks!

**Comment by Lauriichan** [comment]
> If possible, I would like to discuss making this plugin open source so others can continue development on it. Let me know your thoughts, thanks!

I don't know what you are talking about mate, as you can see this plugin is open source....

**Comment by MCHalfAssed** [comment]
> > If possible, I would like to discuss making this plugin open source so others can continue development on it. Let me know your thoughts, thanks!
> 
> I don't know what you are talking about mate, as you can see this plugin is open source....

Indeed it is - Sorry for the confusion, thank you for everything. :)

**Comment by ErythroCraft** [comment]
> > > If possible, I would like to discuss making this plugin open source so others can continue development on it. Let me know your thoughts, thanks!
> > 
> > 
> > I don't know what you are talking about mate, as you can see this plugin is open source....
> 
> Indeed it is - Sorry for the confusion, thank you for everything. :)

ping me if you fixed it.

**Comment by Lauriichan** [comment]
I won't be able to fix it as the issue that you have is not caused by the code available in the github repository meaning the owner itself can only fix it as they are the only one that have the code right now.

**Comment by ErythroCraft** [comment]
> I won't be able to fix it as the issue that you have is not caused by the code available in the github repository meaning the owner itself can only fix it as they are the only one that have the code right now.

Ok. than we do not use this plugin. The updates will take to long and 1.20 is out 4 until 6 monthes.

**Comment by louanfontenele** [comment]
Please update to 1.19.3

**Comment by louanfontenele** [comment]
Me and a friend we update the Lootin to 1.19.3
https://anonfiles.com/5149Qdabze/Lootin_5_4_jar (TEST FIRST ON LOCALHOST)

We will keep future updates on Spigot, we will call it "Name Coming Soon"

We will have a free version available here: "Link Coming Soon"

**Comment by Ashdeuzo** [comment]
Not all heroes wear capes, thanks you very much.

**Comment by Ashdeuzo** [comment]
> Me and a friend we update the Lootin to 1.19.3 https://anonfiles.com/5149Qdabze/Lootin_5_4_jar (TEST FIRST ON LOCALHOST)
> 
> We will keep future updates on Spigot, we will call it "Name Coming Soon"
> 
> We will have a free version available here: "Link Coming Soon"

I can't open chest.
https://paste.helpch.at/hihunobifi.rb

**Comment by louanfontenele** [comment]
> > > > Me and a friend we update the Lootin to 1.19.3 https://anonfiles.com/5149Qdabze/Lootin_5_4_jar (TEST FIRST ON LOCALHOST)
> > > > We will keep future updates on Spigot, we will call it "Name Coming Soon"
> > > > We will have a free version available here: "Link Coming Soon"
> > > 
> > > 
> > > I can't open chest.
> > > https://paste.helpch.at/hihunobifi.rb
> > 
> > 
> > Are you using placeholder api? If yes there is a bug on it. But we already fix it. I'll send the link here later.
> 
> Yes i use placeholder api

https://www.spigotmc.org/resources/looter.108296/

**Comment by Ashdeuzo** [comment]
Thanks,

OhTheDungeonsYou'llGo never work anymore ?

**Comment by louanfontenele** [comment]
> Thanks,
> 
> OhTheDungeonsYou'llGo never work anymore ?
> 
> EDIT: I Speak on your spigot page now

Unfortunately not, because not even the plugin itself (OhTheDungeonsYou'llGo) has been updated, so in the new versions of Minecraft 1.19.3 it doesn't work because it changed some dependencies.

On Spigot's page, the OhTheDungeonsYou'llGo plugin doesn't exist anymore.

**Comment by Lauriichan** [comment]
There is also an alternative in the works at https://github.com/Lauriichan/JustLootIt which hopefully will also provide better performance.
Also: back in january I contacted the original author of Lootin and he said that he currently just doesn't have the time to work on his plugins because of school / university exams.

**Comment by Ashdeuzo** [comment]
> > Thanks,
> > OhTheDungeonsYou'llGo never work anymore ?
> > EDIT: I Speak on your spigot page now
> 
> Unfortunately not, because not even the plugin itself (OhTheDungeonsYou'llGo) has been updated, so in the new versions of Minecraft 1.19.3 it doesn't work because it changed some dependencies.
> 
> On Spigot's page, the OhTheDungeonsYou'llGo plugin doesn't exist anymore.

Check you spigot discussion i give you a link of OTD updated to 1.19.3

**Comment by louanfontenele** [comment]
> There is also an alternative in the works at https://github.com/Lauriichan/JustLootIt which hopefully will also provide better performance. Also: back in january I contacted the original author of Lootin and he said that he currently just doesn't have the time to work on his plugins because of school / university exams.

@Lauriichan if you want, I can add you to our private repository, then you can help build and improve Looter, if you so desire. But thanks for JustLootIt

**Comment by louanfontenele** [comment]
> > > Thanks,
> > > OhTheDungeonsYou'llGo never work anymore ?
> > > EDIT: I Speak on your spigot page now
> > 
> > 
> > Unfortunately not, because not even the plugin itself (OhTheDungeonsYou'llGo) has been updated, so in the new versions of Minecraft 1.19.3 it doesn't work because it changed some dependencies.
> > On Spigot's page, the OhTheDungeonsYou'llGo plugin doesn't exist anymore.
> 
> Check you spigot discussion i give you a link of OTD updated to 1.19.3

I'll check it out. Thank so much.

**Comment by Lauriichan** [comment]
> > There is also an alternative in the works at https://github.com/Lauriichan/JustLootIt which hopefully will also provide better performance. Also: back in january I contacted the original author of Lootin and he said that he currently just doesn't have the time to work on his plugins because of school / university exams.
> 
> @Lauriichan if you want, I can add you to our private repository, then you can help build and improve Looter, if you so desire. But thanks for JustLootIt

Thanks for the offer but I've no interest in working on a plugin based on Lootin.
I'm currently working with different people because of one person that wanted this plugin to continue.

One of those people is the creator of [Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr), the main inspiration of Lootin. We're trying to achieve more than what Lootin was capable of while having better performance. For this to work we're also currently contributing to Spigot to add more events that will help with this.

Also I want to mention that you are breaking the terms of the license that Lootin provides.
You are normally required to disclose the source of any published version of Lootin (even if modified) - which is also one of the reasons why I wouldn't want to help you there.

**Comment by Lauriichan** [comment]
> but I'm sad to think this might have bothered you, at no point did I want to cause frustration

It's not frustrating for me and it doesn't bother me that much, it's just that the original author always wanted that his code was public so that anyone would be able to learn from it / be able to work with it. Its not more or less

**Comment by louanfontenele** [comment]
> > but I'm sad to think this might have bothered you, at no point did I want to cause frustration
> 
> It's not frustrating for me and it doesn't bother me that much, it's just that the original author always wanted that his code was public so that anyone would be able to learn from it / be able to work with it. Its not more or less
> 
> > And a good job with Lootr
Don't worry, I will always credit the author of Lootin.

> Thanks I guess? I don't really understand what you mean with it though xD
I thought you were working on Lootr, but maybe I was wrong, sorry, hahaha. 😂

**Comment by Lauriichan** [comment]
No we're not working on Lootr, we're working with the author of Lootr, that one person that wanted to see this plugin continue really did a lot here.
We're working on [JustLootIt](https://github.com/Lauriichan/JustLootIt), an alternative spigot plugin I started to make.
It will be more similar to Lootr than Lootin though.
