### ISSUE TITLE
Plugin stop working under Paper with CB packge relocation 

### ISSUE THREAD

**Issue by YuanYuanOwO** [sachingorkar102/Lootin-plugin#25]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

```
[19:57:50] [Server thread/INFO]: [Lootin] Enabling Lootin v8.3
[19:57:50] [Server thread/ERROR]: Error occurred while enabling Lootin v8.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.github.sachin.prilib.Prilib.<init>(Prilib.java:43) ~[Lootin-8.3.jar:?]
	at com.github.sachin.lootin.Lootin.onEnable(Lootin.java:73) ~[Lootin-8.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by sachingorkar102** [comment]
fixed in 8.5
